version: "3.7"
services:
  config:
    image: steeltoeoss/config-server:latest
    ports:
      - "8888:8888"
    environment:
      - spring.cloud.config.server.git.uri=https://github.com/fjb4/steeltoe-config-repo
  eureka:
    image: steeltoeoss/eurekaserver:latest
    ports:
      - "8761:8761"
